const demoPresets = [
  {
    name: "Default",
    settings: {
      pointDensity: 30,
      attractDistanceRange: [15, 30],
      attractForceRange: {
        value: [0, 10],
        inverted: false,
      },
      repelDistanceRange: [0, 20],
      repelForceRange: {
        value: [0, 1000],
        inverted: true,
      },
      maxLineLength: 60,
      backgroundColor: "#000000",
      pointColor: "#008080",
      lineColor: "#ADD8E6",
    },
  },
  {
    name: "Grid",
    settings: {
      pointDensity: 30,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 60],
      repelForceRange: {
        value: [0, 2500],
        inverted: true,
      },
      maxLineLength: 60,
      backgroundColor: "#000000",
      pointColor: "#0096ff",
      lineColor: "#00fdff",
    },
  },
  {
    name: "Consume",
    settings: {
      pointDensity: 30,
      attractDistanceRange: [10, 100],
      attractForceRange: [200, 400],
      repelDistanceRange: [0, 80],
      repelForceRange: {
        value: [200, 800],
        inverted: true,
      },
      maxLineLength: 20,
      backgroundColor: "#8b0000",
      pointColor: "#ff5733",
      lineColor: "#ffd700",
    },
  },
  {
    name: "Water",
    settings: {
      pointDensity: 16,
      attractDistanceRange: [0, 75],
      attractForceRange: [0, 1024],
      repelDistanceRange: [0, 90],
      repelForceRange: {
        value: [1400, 4100],
        inverted: true,
      },
      maxLineLength: 90,
      backgroundColor: "#0096ff",
      pointColor: "#0096ff",
      lineColor: "#00fdff",
    },
  },
  {
    name: "Fractal",
    settings: {
      pointDensity: 30,
      attractDistanceRange: [0, 500],
      attractForceRange: [5000, 6000],
      repelDistanceRange: [0, 500],
      repelForceRange: {
        value: [7000, 9000],
        inverted: true,
      },
      maxLineLength: 300,
      backgroundColor: "#ffffff",
      pointColor: "#ff9300",
      lineColor: "#9437ff",
    },
  },
  {
    name: "Web",
    settings: {
      pointDensity: 30,
      attractDistanceRange: [15, 55],
      attractForceRange: [0, 10],
      repelDistanceRange: [0, 20],
      repelForceRange: {
        value: [0, 1000],
        inverted: true,
      },
      maxLineLength: 250,
      backgroundColor: "#000000",
      pointColor: "#008080",
      lineColor: "#ADD8E6",
    },
  },
  {
    name: "Storm",
    settings: {
      pointDensity: 60,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 70],
      repelForceRange: {
        value: [4000, 6000],
        inverted: true,
      },
      maxLineLength: 0,
      backgroundColor: "#cccccc",
      pointColor: "#ffffff",
      lineColor: "#000000",
    },
  },
  {
    name: "Lines",
    settings: {
      pointDensity: 1,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 0],
      repelForceRange: [0, 0],
      maxLineLength: 800,
      backgroundColor: "#000000",
      pointColor: "#000000",
      lineColor: "#0080ff",
    },
  },
  {
    name: "Sun",
    settings: {
      pointDensity: 20,
      attractDistanceRange: [0, 500],
      attractForceRange: [4500, 6000],
      repelDistanceRange: [0, 500],
      repelForceRange: {
        value: [4500, 7500],
        inverted: true,
      },
      maxLineLength: 115,
      backgroundColor: "#f1f480",
      pointColor: "#f1d150",
      lineColor: "#d0b600",
    },
  },
];
