/*
	presets.js
	
    Copyright (C) 2015 - 2021 Corey Shuman <ctshumancode@gmail.com>
	
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

const demoPresets = [
  {
    name: "Galaxy",
    settings: {
      pointDensity: 30,
      pointSize: 3,
      friction: 300,
      frictionMinVelocity: 5000,
      attractDistanceRange: [15, 30],
      attractForceRange: {
        value: [0, 10],
        inverted: false,
      },
      repelDistanceRange: [0, 20],
      repelForceRange: {
        value: [0, 1000],
        inverted: true,
      },
      maxLineLength: 60,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "repel",
      backgroundColor: "#000000",
      pointColor: "#008080",
      lineColor: "#ADD8E6",
      pointInteractColor: "#dd3311",
    },
  },
  {
    name: "Grid",
    settings: {
      pointDensity: 30,
      pointSize: 3,
      friction: 300,
      frictionMinVelocity: 5000,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 60],
      repelForceRange: {
        value: [0, 2500],
        inverted: true,
      },
      maxLineLength: 60,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 175,
      maxInteractForce: 10000,
      interactMode: "repel",
      backgroundColor: "#000000",
      pointColor: "#0096ff",
      lineColor: "#00fdff",
      pointInteractColor: "#dd33dd",
    },
  },
  {
    name: "Consume",
    settings: {
      pointDensity: 20,
      pointSize: 3,
      friction: 150,
      frictionMinVelocity: 2500,
      attractDistanceRange: [10, 150],
      attractForceRange: {
        value: [100, 400],
        inverted: true,
      },
      repelDistanceRange: [0, 80],
      repelForceRange: {
        value: [200, 800],
        inverted: true,
      },
      maxLineLength: 20,
      lineSize: 1,
      screenBlur: 9970,
      maxInteractDistance: 60,
      maxInteractForce: 6200,
      interactMode: "attract",
      backgroundColor: "#8b0000",
      pointColor: "#ff5733",
      lineColor: "#ffd700",
      pointInteractColor: "#ffcc33",
    },
  },
  {
    name: "Water",
    settings: {
      pointDensity: 16,
      pointSize: 3,
      friction: 675,
      frictionMinVelocity: 3300,
      attractDistanceRange: [0, 75],
      attractForceRange: [0, 1024],
      repelDistanceRange: [0, 90],
      repelForceRange: {
        value: [1400, 4100],
        inverted: true,
      },
      maxLineLength: 90,
      lineSize: 1,
      screenBlur: 6700,
      maxInteractDistance: 450,
      maxInteractForce: 1500,
      interactMode: "attract",
      backgroundColor: "#0096ff",
      pointColor: "#0096ff",
      lineColor: "#00fdff",
      pointInteractColor: "#0096ff",
    },
  },
  {
    name: "Fractal",
    settings: {
      pointDensity: 30,
      pointSize: 3,
      friction: 300,
      frictionMinVelocity: 5000,
      attractDistanceRange: [0, 500],
      attractForceRange: [5000, 6000],
      repelDistanceRange: [0, 500],
      repelForceRange: {
        value: [7000, 9000],
        inverted: true,
      },
      maxLineLength: 300,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "repel",
      backgroundColor: "#ffffff",
      pointColor: "#ff9300",
      lineColor: "#9437ff",
      pointInteractColor: "#ff9300",
    },
  },
  {
    name: "Web",
    settings: {
      pointDensity: 30,
      pointSize: 3,
      friction: 700,
      frictionMinVelocity: 2500,
      attractDistanceRange: [15, 55],
      attractForceRange: [0, 10],
      repelDistanceRange: [0, 20],
      repelForceRange: {
        value: [0, 1000],
        inverted: true,
      },
      maxLineLength: 250,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 180,
      maxInteractForce: 3000,
      interactMode: "attract",
      backgroundColor: "#000000",
      pointColor: "#000000",
      lineColor: "#ADD8E6",
      pointInteractColor: "#000000",
    },
  },
  {
    name: "Storm",
    settings: {
      pointDensity: 60,
      pointSize: 3,
      friction: 300,
      frictionMinVelocity: 5000,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 70],
      repelForceRange: {
        value: [4000, 6000],
        inverted: true,
      },
      maxLineLength: 0,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "repel",
      backgroundColor: "#cccccc",
      pointColor: "#ffffff",
      lineColor: "#000000",
      pointInteractColor: "#cccccc",
    },
  },
  {
    name: "Lines",
    settings: {
      pointDensity: 1,
      pointSize: 19,
      friction: 200,
      frictionMinVelocity: 7500,
      attractDistanceRange: [0, 0],
      attractForceRange: [0, 0],
      repelDistanceRange: [0, 0],
      repelForceRange: [0, 0],
      maxLineLength: 800,
      lineSize: 38,
      screenBlur: 9750,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "repel",
      backgroundColor: "#000000",
      pointColor: "#0080ff",
      lineColor: "#0080ff",
      pointInteractColor: "#0080ff",
    },
  },
  {
    name: "Sun",
    settings: {
      pointDensity: 20,
      pointSize: 3,
      friction: 300,
      frictionMinVelocity: 5000,
      attractDistanceRange: [0, 500],
      attractForceRange: [4500, 6000],
      repelDistanceRange: [0, 500],
      repelForceRange: {
        value: [4500, 7500],
        inverted: true,
      },
      maxLineLength: 115,
      lineSize: 1,
      screenBlur: 6000,
      maxInteractDistance: 335,
      maxInteractForce: 7000,
      interactMode: "repel",
      backgroundColor: "#f1f480",
      pointColor: "#f1d150",
      lineColor: "#d0b600",
      pointInteractColor: "#c48517",
    },
  },
  {
    name: "Balloons",
    settings: {
      pointDensity: 1,
      pointSize: 30,
      friction: 0,
      frictionMinVelocity: 0,
      attractDistanceRange: [650, 955],
      attractForceRange: {
        value: [0, 125],
        inverted: true,
      },
      repelDistanceRange: [60, 62],
      repelForceRange: {
        value: [10000, 10000],
        inverted: true,
      },
      maxLineLength: 0,
      lineSize: 1,
      screenBlur: 0,
      maxInteractDistance: 250,
      maxInteractForce: 4500,
      interactMode: "repel",
      backgroundColor: "#33346b",
      pointColor: "#ff85eb",
      lineColor: "#ADD8E6",
      pointInteractColor: "#42d9ff",
    },
  },
  {
    name: "Fireflies",
    settings: {
      pointDensity: 5,
      pointSize: 3,
      friction: 50,
      frictionMinVelocity: 5000,
      attractDistanceRange: [1, 100],
      attractForceRange: {
        value: [0, 0],
        inverted: false,
      },
      repelDistanceRange: [200, 300],
      repelForceRange: {
        value: [0, 100],
        inverted: false,
      },
      maxLineLength: 70,
      lineSize: 6,
      screenBlur: 6000,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "attract",
      backgroundColor: "#250052",
      pointColor: "#fff700",
      lineColor: "#250052",
      pointInteractColor: "#250052",
    },
  },
  {
    name: "Embers",
    settings: {
      pointDensity: 40,
      pointSize: 1,
      friction: 50,
      frictionMinVelocity: 5000,
      attractDistanceRange: [1, 100],
      attractForceRange: {
        value: [0, 0],
        inverted: false,
      },
      repelDistanceRange: [0, 0],
      repelForceRange: {
        value: [0, 0],
        inverted: false,
      },
      maxLineLength: 37,
      lineSize: 9,
      screenBlur: 9360,
      maxInteractDistance: 60,
      maxInteractForce: 3000,
      interactMode: "attract",
      backgroundColor: "#660f0f",
      pointColor: "#fffb94",
      lineColor: "#544f59",
      pointInteractColor: "#ffab1a",
    },
  },
];
